### ISSUE TITLE
[BUG] Toast shows incorrect mod count (race condition)

### ISSUE THREAD

**Issue by Hexcede** [DeathsGun/ModManager#108]
**Describe the bug**
When loading the game, the toast can display before all mods have actually been checked for updates. This results in the toast showing an incorrect number of mods (e.g. 3), but when entering the menu there are actually more (e.g. 13, I have a lot of mods that don't respect semver apparently).

**To Reproduce**
1. Install a few mods which don't respect semver or have multiple out of date mods
2. Launch the game so that the toast will display
3. Sometimes the correct count is displayed but usually if the game window is focused it will pop up immediately with an incorrect count

**Expected behavior**
The toast displays the correct number of mods.

**Screenshots**
Incorrect number of mods displayed:
![image](https://user-images.githubusercontent.com/8394472/144640980-ad4609b0-f431-4a01-a086-1fd33515c183.png)

Outdated mods in manager (There are 13):
![image](https://user-images.githubusercontent.com/8394472/144641130-9da738d2-145f-4d51-a9fa-c8733d8927c2.png)

**Please complete the following information:**
 - OS: `Linux (KDE + Ubuntu)`
 - Minecraft version: `1.17.1`
 - Version: `1.2.0`

**Comment by DeathsGun** [comment]
Yeah I noticed that one too but haven't had time to track it down 
Thank you for finding the reason for  that one

**Comment by DeathsGun** [comment]
This should fix your problem:
[modmanager-1.2.0-alpha+1.17.jar.zip](https://github.com/DeathsGun/ModManager/files/7656476/modmanager-1.2.0-alpha%2B1.17.jar.zip)
