### ISSUE TITLE
Update all button

### ISSUE THREAD

**Issue by luximus-hunter** [DeathsGun/ModManager#114]
**Is your feature request related to a problem? Please describe.**
Sometimes a lot of nods get updated at the same time. If that happens you need to update all mods separately.

**Describe the solution you'd like**
In the list of updatable mods, there should be a button to update all mods in that list.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by DeathsGun** [comment]
Hi thank you for your interest in making ModManager better! The feature you have described has already been implemented in #100 and will be shipped in the next release.

In the mean time you can compile the newest version from this yourself or I can provide you one

**Comment by luximus-hunter** [comment]
Oh sick! I'll try to compile within a few minutes

**Comment by luximus-hunter** [comment]
> Oh sick! I'll try to compile within a few minutes

@DeathsGun I can't seem to get the build to work. Is there something else that run the `gradlew.bat` file?

**Comment by DeathsGun** [comment]
Do you have a Java jdk installed?

**Comment by DeathsGun** [comment]
Normally you go to the directory and open a cmd there and enter the following command: gradlew.bat clean build

**Comment by luximus-hunter** [comment]
> gradlew.bat clean build

I should have yeah

> Normally you go to the directory and open a cmd there and enter the following command: gradlew.bat clean build

Ill try this real quick

**Comment by luximus-hunter** [comment]
@DeathsGun it didnt work. Do you have a discord or something else we can maybe chat a bit easier?

**Comment by DeathsGun** [comment]
Yeah my name tag on discord is DeathsGun#2539 but it's 23:42 (11:42pm) now and will now go to bed. I will reply you tomorrow then.

**Comment by luximus-hunter** [comment]
Aye, sounds good

**Comment by RDKRACZ** [comment]
It's building fine for me, you should paste the error.
