### ISSUE TITLE
[1.18] ModManager asks to update already updated mods because of a different file name

### ISSUE THREAD

**Issue by ZtereoHYPE** [DeathsGun/ModManager#115]
**Describe the bug**
ModManager will ask to update many mods which are already updated due to different file names possibly on modrinth. Once the mods have been updated they disappear form the updateable mod list until the client is restarted, after which modmanager will ask again to update those to the "new" version.

**To Reproduce**
1. Download presence footsteps, iris, lithium, Dynamic FPS and install them manually
2. launch minecraft with mod manager installed
3. try to update the mods from mod manager 
4. restart the game and notice the popups again

**Expected behavior**
I expected the mods to stay updated once updated, or to not request to be updated when already at the latest version

**Screenshots**
![screenshot 1](https://user-images.githubusercontent.com/57519662/145694112-f81be7ef-b469-4988-b47b-0a4dcfe26a4f.png)
![screenshot 2](https://user-images.githubusercontent.com/57519662/145694114-93115eb8-65bb-45d8-b5c4-4f891cf37014.png)

**Please complete the following information:**
 - OS: macOS Monterey
 - Minecraft version 1.18
 - Version 1.2.1+1.18

**Logs**
[latest.log](https://github.com/DeathsGun/ModManager/files/7697859/latest.log)

**Comment by DeathsGun** [comment]
Hi sorry for the late answer, the bug you reported has been fixed in #101 for 1.17 but also needs to get ported to the 1.18 and 1.16 version.
I will use this issue for tracking that

**Comment by DeathsGun** [comment]
Done i merged it into 1.18 and it will be shipped with the next release
