### ISSUE TITLE
Help needed: access to modrinth api is denied

### ISSUE THREAD

**Issue by ShadowThijs** [DeathsGun/ModManager#116]
Whenever I go to the mod manager in mod menu, I get the message: 
Failed to parse response: access denied ("java.net.URLPermission" "https://api.modrinth.com/api/v1/tag/category" "GET:User-Agent")
I don't know if there is something I did wrong on my end, but I would like to continue to use Mod Manager.
If you know the answer, feel free to comment on this post!
Thanks!

**Comment by DeathsGun** [comment]
I need more info

**Comment by ShadowThijs** [comment]
Figured it out already, there seems to be a problem / interference with the mod NotEnoughCrashes version 4.1.3 for 1.18
The latest_crash log is NEC loaded and latest log is NEC not loaded.

[latest_crash.log](https://github.com/DeathsGun/ModManager/files/7727329/latest_crash.log)
[latest.log](https://github.com/DeathsGun/ModManager/files/7727330/latest.log)

**Comment by DeathsGun** [comment]
Sorry for the late answer from the i can only see that's something with your jvm security manager is weird configured.
I don't know if NEC  messes around with the security manager.

Ps:  Nee ik ben niet so een grote fan van Formulare 1
