### ISSUE TITLE
[BUG] ModManger says that I need to update my mods despite being the latest version

### ISSUE THREAD

**Issue by MiningJack777** [DeathsGun/ModManager#118]
**Describe the bug**
The bug appears as mislabeling several of my mods as needing to be updated, but when I go to update, it fails and throws an error saying that the file was already in the directory of my Minecraft mods.

**To Reproduce**
1. Install 1.16.5 Fabric Loader and 1.16.5 Version of ModManger with ModMenu and 1.16.5 Sodium pulled directly off Modrinth
2. Open game and go to Mod Menu
3. Click on Sodium
4. See that the icon to hide updates is shown.
5. Open the installer menu in ModManger
6. Filter by Updatable
7. See that it says Sodium is outdated.
8. Try to update
9. Get an error saying that the process could not be completed because the file was already present.

**Expected behavior**
I expected that this would NOT show that I need to update the Mod BECAUSE IT IS THE LATEST (1.16.5) VERSION OF THE MOD

**Screenshots**
<img width="884" alt="error" src="https://user-images.githubusercontent.com/92181216/148556362-c969c6f8-9acd-49eb-ac7e-3639249cc659.png">

 - Windows 10 Pro on Surface 2
 - Fabric Launcher 0.12.12 
 - Minecraft Version: 1.16.5 
 - ModManger 1.2.0+1.16

**Comment by MiningJack777** [comment]
Also, I believe the version of ModManger I am using is from 11/24/2021 based on my file date

**Comment by DeathsGun** [comment]
Can you try the version provided [here](https://github.com/DeathsGun/ModManager/issues/12#issuecomment-1004252013)?

**Comment by DeathsGun** [comment]
You can re open it if required
