### ISSUE TITLE
[BUG] Latest and local version naming difference make ModManager believe update available

### ISSUE THREAD

**Issue by KrisCris** [DeathsGun/ModManager#119]
**Describe the bug**

<img width="330" alt="image" src="https://user-images.githubusercontent.com/38860226/148738887-bdc5b4bf-d1a1-48b9-a579-842e145ee5df.png">

I am not sure if this can be fixed by ModManager, or perhaps that mod author has to properly label the version online?

**Please complete the following information:**
 - Version: 1.2.1 - 1.18

**Comment by DeathsGun** [comment]
Can you try [this](https://github.com/DeathsGun/ModManager/suites/4870648757/artifacts/138952067) version?

**Comment by KrisCris** [comment]
works fine for me :)
thanks!
