### ISSUE TITLE
Error when trying to update mod

### ISSUE THREAD

**Issue by kuzeeeyk** [DeathsGun/ModManager#15]
^
![image](https://media.discordapp.net/attachments/864769828913283074/879656482847723550/unknown.png)

**Comment by DeathsGun** [comment]
Ok this is problem with the file handling of windows itself. 
I think i need to change the method to deleteOnExit()

**Comment by DeathsGun** [comment]
Can you check if the problem persist with this version:
[modmanager-1.0.1-alpha.zip](https://github.com/DeathsGun/ModManager/files/7038386/modmanager-1.0.1-alpha.zip)

**Comment by kuzeeeyk** [comment]
It gives me same error

**Comment by DeathsGun** [comment]
And with this?
[modmanager-1.0.1-alpha.zip](https://github.com/DeathsGun/ModManager/files/7038692/modmanager-1.0.1-alpha.zip)

**Comment by kuzeeeyk** [comment]
Works awesomely.
