### ISSUE TITLE
Showing updates for mods that i don't have in my mods

### ISSUE THREAD

**Issue by kuzeeeyk** [DeathsGun/ModManager#18]
I guess it happens because of search system of modmanager, it show Litematica as addon of Litematica (GrabcraftLitematic)
![image](https://i.imgur.com/0b6WnvV.png)

**Comment by DeathsGun** [comment]
Can i have your log?

**Comment by kuzeeeyk** [comment]
[latest.log](https://github.com/DeathsGun/ModManager/files/7038628/latest.log)
also when i click to update button on these type of mods (that i dont have), it says couldnt find jar for x

**Comment by DeathsGun** [comment]
Ah it shows up because GrabcraftLitematic is the only litematica mod on modrinth
I need to change the update system to a clearer one.

**Comment by DeathsGun** [comment]
Can you check this again with this version:
[Artifacts.zip](https://github.com/DeathsGun/ModManager/suites/3581836905/artifacts/86153967)

**Comment by kuzeeeyk** [comment]
fixed. probably... that build fixed this problem but i have very similar problem so i'll write this to here

![image](https://i.imgur.com/7sStrHN.png)

i dont have this mods too but diffirent side of them is giving me error while trying to update:
![image](https://i.imgur.com/ozr5bc8.png)

**Comment by DeathsGun** [comment]
ah libzoomer is probably part of OkZoomer think the detection of mods in mods isn't working correctly in some cases
