### ISSUE TITLE
Wrong mod icons

### ISSUE THREAD

**Issue by kuzeeeyk** [DeathsGun/ModManager#22]
I was updating my mods from ModManager. After updating some mods my mod's icons got changed to wrong ones.

![image](https://i.imgur.com/6PWGRsJ.png)

**Comment by DeathsGun** [comment]
Can you check this again with this possible fix:
[Artifacts.zip](https://github.com/DeathsGun/ModManager/suites/3581489220/artifacts/86141556)

**Comment by kuzeeeyk** [comment]
I tested it, and didn't noticed any problems so far. So it's fixed i guess.
