### ISSUE TITLE
[BUG] Error when updating mod.

### ISSUE THREAD

**Issue by kuzeeeyk** [DeathsGun/ModManager#23]
**Describe the bug**
An error appears while im trying to update "OkZoomer"

**To Reproduce**
1. Go to 'Mod update page'
2. Click on 'Update'

**Expected behavior**
Should get updated instead of error

**Screenshots**
![image](https://i.imgur.com/KeiDQkt.png)

**Please complete the following information:**
 - OS: Windows 10 Home Single Language - Build 21390.co_release.210521-1658
 - Minecraft version: 1.17.1
 - Version: 1.0.1-alpha

**Logs**
Latest log: [latest.log](https://github.com/DeathsGun/ModManager/files/7039121/latest.log)

**Additional context**
I noticed this problem in only OkZoomer mod, idk if theres problem in any other mod.

**Comment by DeathsGun** [comment]
From the exception it looks like that your installed OkZoomer mod is corrupt i would suggest removing the mod and reinstalling it through ModManager
