### ISSUE TITLE
[1.17.1] [1.0.0-alpha] Crash while clicking on the Mod Manager button

### ISSUE THREAD

**Issue by Felix14-v2** [DeathsGun/ModManager#28]
**Description**
Minecraft crashes after clicking on the Mod Manager menu button.

**To Reproduce**
1. Launch MC
2. Click on Mod Menu button
3. Click on Mod Manager button
4. Get crash

**[Demo](https://youtu.be/ZRxunZ1utmM?t=50)**

**Technical Info:**
 - Windows 10
 - Java 16 (AdoptOpenJDK, jre-16.0.1.9-hotspot)
 - Minecraft 1.17.1
 - Fabric Loader 0.11.6
 - Fabric API 0.39.0 1.17
 - Mod Manager 1.0.0-alpha

**Logs**
[latest.log](https://github.com/DeathsGun/ModManager/files/7041602/latest.log)
[crash-2021-08-24_22.12.29-client.txt](https://github.com/DeathsGun/ModManager/files/7041604/crash-2021-08-24_22.12.29-client.txt)

**Comment by DeathsGun** [comment]
Hi thank you for reporting this bug with so much detail!

Fortunately it has been fixed in 1.0.1+1.17.1-alpha which you can download [here](https://modrinth.com/mod/modmanager/version/gGSLHqJK)

**Comment by Felix14-v2** [comment]
> Fortunately it has been fixed in 1.0.1
Thanks! You managed to fix the problem before I sent the report :)

**Comment by DeathsGun** [comment]
> > Fortunately it has been fixed in 1.0.1
> 
> Thanks! You managed to fix the problem before I sent the report :)

Someone was just faster #13
