### ISSUE TITLE
[BUG] NullPointerException is often thrown when update a mod

### ISSUE THREAD

**Issue by MineCommanderCN** [DeathsGun/ModManager#34]
**Describe the bug**
Mod updating often fails and throw a NullPointerException in Show error page. I tried to update 4 mods and this issue happened twice.

**To Reproduce**
This error has a random chance to happen and not every try will reproduce it.
1. Get a mod need to be updated;
2. Open ModManager menu;
3. Double click the outdated mod and click Update;
4. A button "Show error" appears, click in and see the error.

**Screenshots**
Tested fail-to-update mods:
![image](https://user-images.githubusercontent.com/59791306/130739234-479a22e7-fd02-49f7-82e7-a60d27c3fd95.png)

Error report:
![image](https://user-images.githubusercontent.com/59791306/130739277-1fca280f-c993-4ad0-bb0e-dd284e220587.png)

Two mods have the same report content.

** Please complete the following information:**
 - OS: Windows 10 Pro 21H1
 - Minecraft version: 1.17.1 with Fabric 0.11.6 and Fabric API 0.39.1
 - Mod version 1.0.1-alpha

** Logs **
Latest log: [latest.log](https://github.com/DeathsGun/ModManager/files/7044263/latest.log)
Mod list: [modlist.txt](https://github.com/DeathsGun/ModManager/files/7044264/modlist.txt)

Crash report (if any): no crashes

**Comment by DeathsGun** [comment]
Thank you for the report I will look into it

**Comment by DeathsGun** [comment]
Does this fix your problem?
[Artifacts.zip](https://github.com/DeathsGun/ModManager/suites/3588647362/artifacts/86401702)

**Comment by MineCommanderCN** [comment]
> Does this fix your problem?
> [Artifacts.zip](https://github.com/DeathsGun/ModManager/suites/3588647362/artifacts/86401702)

Detail Armor Bar doesn't give errors any more, but Reese's Sodium Options reports a new one:
![image](https://user-images.githubusercontent.com/59791306/130744605-1a847c5d-69a3-4307-a1fe-3f31c21ce65e.png)

Logs: 
[latest.log](https://github.com/DeathsGun/ModManager/files/7044575/latest.log)

**Comment by MineCommanderCN** [comment]
Also there is a small bug, sometimes the update will download a Forge version of a mod.
![image](https://user-images.githubusercontent.com/59791306/130745419-15aa5017-c614-45d1-80b3-178981d94b89.png)
Would you mind me opening another issue?

**Comment by DeathsGun** [comment]
It should find it because it ignores the file name an checks only the fabric.mod.json provided by the mod developer.
I think it messes Sodium Extra and Sodium Options up

**Comment by DeathsGun** [comment]
> Also there is a small bug, sometimes the update will download a Forge version of a mod.
> ![image](https://user-images.githubusercontent.com/59791306/130745419-15aa5017-c614-45d1-80b3-178981d94b89.png)
> Would you mind me opening another issue?

Yes please
