### ISSUE TITLE
Enhancement: Be able to sort by relevance, download count, etc.

### ISSUE THREAD

**Issue by aqualxx** [DeathsGun/ModManager#45]
It would be much more user-friendly to find mods if we could sort by relevance, download count, etc. Currently, it is hard to find the mods you are looking for without having to go through dozens of pages.

**Comment by aqualxx** [comment]
Oops, can you remove the bug label and replace it with enhancement?

**Comment by DeathsGun** [comment]
The code for this is already written what's missing is only the user interface
