### ISSUE TITLE
没有中文

### ISSUE THREAD

**Issue by buiawpkgew1** [DeathsGun/ModManager#47]
![QQ截图20210830165258](https://user-images.githubusercontent.com/71136405/131313507-c9c76f37-7fe9-45bf-baa0-38a1663256df.png)

**Comment by MineCommanderCN** [comment]
下次报告bug请使用issue模板并使用英文。
中文翻译目前没有实装，请到1.17分支下载最新的artifacts体验

**Comment by DeathsGun** [comment]
中文将只在1.1.0+1.17.1-alpha版本中发布。请再耐心等待一下。

用deepL.com翻译的
