### ISSUE TITLE
[BUG] Extreme CPU overload

### ISSUE THREAD

**Issue by Felix14-v2** [DeathsGun/ModManager#48]
**Description**
For some reason, this mod consumes an incredibly large amount of CPU resources both in the game itself and in the main menu.

**To Reproduce**
1. Install Fabric 1.17.1
2. Install Fabric API, ModMenu and ModManager
2. Run your Minecraft
3. Open Task Manager
4. Observe CPU overload
5*. (and immerse yourself in the Microsoft Flight Simulator sound atmosphere, if you are playing on laptop)

**Expected behavior**

![2021-09-01 23-29-08 mp4_snapshot_00 51_ 2021 09 01_23 59 19](https://user-images.githubusercontent.com/75726196/131744492-c4048997-c1ae-44cf-bc01-f07c37e2d739.png)
![2021-09-01 23-29-08 mp4_snapshot_00 54_ 2021 09 01_23 47 49](https://user-images.githubusercontent.com/75726196/131743305-9f6c4deb-737b-466b-902f-b732bd38db30.png)

Comparison with enabled Mod Manager and without it: [[Demo]](https://youtu.be/CiIUXnH-NVE)
Without any optimization mods the situation is even worse: [[Demo]](https://youtu.be/GMzWcxZNm6E)
Also, the speed of RAM garbage generation is about 1.5 GB/s (!). In normal, it is about 2-3 MB/s.

**Technical information**
 - Windows 10
 - Minecraft 1.17.1
 - Mod Manager v1.0.1+1.17-alpha
 - Fabric API 0.39.0
 - Java: JRE 16.0.1.9 (AdoptOpenJDK hotspot)

**Logs** (nothing interesting there, I think)
[with my modpack](https://github.com/DeathsGun/ModManager/files/7094275/2021-09-01-4.log)
[only ModManager](https://github.com/DeathsGun/ModManager/files/7094265/latest.log)

**Comment by Felix14-v2** [comment]
[Here](https://youtu.be/AmVR-wqelSk) you can see how fast is the garbage generation (other bugreport).

**Comment by DeathsGun** [comment]
Does this fix your issues? 

[Artifacts.zip](https://github.com/DeathsGun/ModManager/suites/3672663129/artifacts/89352763)

**Comment by Felix14-v2** [comment]
Absolutely.
