### ISSUE TITLE
ThatOrThis compatibility

### ISSUE THREAD

**Issue by Felix14-v2** [DeathsGun/ModManager#50]
**Problem**
[ThatOrThis](https://github.com/EZForever/ThatOrThis) is a mod that allows you to load mods from additional directories (for e.g. 'mods\Technical\GUI\ModManager'). At the moment, ModManager shows this error while trying to update such mods:
.`java.lang.Exception: Couldn't find jar for [modname]`
(`	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.31) ~[?:?]`)
.`	at xyz.deathsgun.modmanager.tasks.ModUpdateTask.execute(ModUpdateTask.java:40) ~[modmanager-1.0.2+1.17-alpha.jar:?]`
.`	at xyz.deathsgun.modmanager.api.manipulation.ManipulationTask.executeTask(ManipulationTask.java:47) [modmanager-1.0.2+1.17-alpha.jar:?]`
.`	at xyz.deathsgun.modmanager.services.ManipulationService.run(ManipulationService.java:49) [modmanager-1.0.2+1.17-alpha.jar:?]`

**Decision**
Is it possible to add checking of custom paths from thatorthis configs (config\thatorthis\rules.json)?
I hope, [this](https://github.com/EZForever/ThatOrThis/blob/master/rules.example.json5) should be useful.

**Comment by DeathsGun** [comment]
Yeah this shouldn't be that much work

**Comment by MineCommanderCN** [comment]
I don't think this is a compatibility issue. I have got the same problem before when trying to update other mods, and it has just gone after several days. Maybe it is just because of Modrinth's API issue or network lag. But ModManager could do something on itself to work out this problem.

**Comment by DeathsGun** [comment]
ModManager looks only in mods/ for jar files so it only needs to als look in subdirectories. 
And for the error that it can't find the jar is now handled differently than in the kotlin rewrite. It will check first if the jar file exists and then for updates for the mod

**Comment by DeathsGun** [comment]
Did you test this again with 1.1.0?

**Comment by Felix14-v2** [comment]
Of course, works perfectly 👍
I think, this issue can be closed. If I will find some problems, we can always reopen it.
