### ISSUE TITLE
[BUG] Old version stays behind

### ISSUE THREAD

**Issue by luximus-hunter** [DeathsGun/ModManager#51]
**Describe the bug**
Currently, the old version of an updated mod doesn't get removed, causing errors at startup

**To Reproduce**
1. Update a mod
2. Exit the game
3. Start the game again with updated mods

**Expected behavior**
When updating a mod, remove the older version

**Screenshots**
![image](https://user-images.githubusercontent.com/49814847/132123963-3a3c6634-9c0e-4b6f-8fa8-d464c7f51514.png)

** Please complete the following information:**
 - OS: Windows 10 Pro
 - Minecraft version: 1.17.1
 - Version 1.0.2-alpha

**Additional note**
When saving the file, try to look for any mods with a similar name and ignore the numbers, and delete it.

**Comment by DeathsGun** [comment]
@PKMNPlatin

**Comment by DeathsGun** [comment]
Does this also happen with v1.1.0+1.17-alpha?

[modmanager-1.1.0+1.17-alpha.jar.zip](https://github.com/DeathsGun/ModManager/files/7239362/modmanager-1.1.0%2B1.17-alpha.jar.zip)

**Comment by DeathsGun** [comment]
I will close this when the issue persist feel free to open this again

**Comment by DeathsGun** [comment]
Opening again because of #66

**Comment by keatit71** [comment]
My problem is it also downloads the wrong version of a mod that is for a older version of minecraft

**Comment by DeathsGun** [comment]
Can you open a separate issue for that one and upload you log files to that

**Comment by DeathsGun** [comment]
Does this fix the problem?

[modmanager-1.1.0-alpha+1.17.jar.zip](https://github.com/DeathsGun/ModManager/files/7292048/modmanager-1.1.0-alpha%2B1.17.jar.zip)

**Comment by keatit71** [comment]
Tried that version and it removes old versions of updated mods.
