### ISSUE TITLE
[BUG] Mods flagged outdated while they're actually up to date

### ISSUE THREAD

**Issue by FPSUsername** [DeathsGun/ModManager#52]
**Describe the bug**
Whenever I manually update a mod that's available on modrinth and curseforge (downloaded the mod from curseforge because it's not updated on modrinth yet), the modmanager flags the mod as outdated.
In addition, for Mousewheelie the modmanager downloads an outdated version (even though it's up to date on modrinth)

**To Reproduce**
1. Install the latest [mousewheelie](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie) mod (currently version `mousewheelie-1.7.3-newconfig.3+mc1.17.1-pre1`
2. Install the mod
3. Launch Minecraft and the mod manager
4. Mod is flagged outdated
5. Update the mod through the mod manager and see that it downloads version `mousewheelie-1.7.3+mc1.17.1-pre1`

**Expected behavior**
The mod manager should know that it's up to date

**Screenshots**
![Screenshot_20210912_140322](https://user-images.githubusercontent.com/10143926/132987055-c4a70b41-4eaa-4d03-bb32-6bc86cd94bad.png)
![Screenshot_20210912_141121](https://user-images.githubusercontent.com/10143926/132987057-32ebdece-e33f-4827-ae07-761bb8a39015.png)

**Please complete the following information:**
 - OS: Arch Linux
 - Minecraft version: 1.17.1
 - Version 1.0.2-alpha

**Logs**
Latest log: https://pastebin.com/T9rLHVTi
(it also contains an error where it can't find a jar for LibZoomer, I think that's part of the [OkZoomer](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer) mod)

**Comment by DeathsGun** [comment]
The log isn't available anymore on pastebin. Can you upload it here directly via drag n drop?

**Comment by FPSUsername** [comment]
[2021-09-12-2.log](https://github.com/DeathsGun/ModManager/files/7150044/2021-09-12-2.log)

**Comment by DeathsGun** [comment]
Looks like mousewheelie isn't following the [SemVer](https://semver.org/) versioning scheme which fabric has implemented [here](https://github.com/FabricMC/fabric-loader/blob/master/src/main/java/net/fabricmc/loader/api/SemanticVersion.java).
I could fix so that when two versions are the same the release date is compared and the newer gets selected

**Comment by FPSUsername** [comment]
Oh okay, that makes sense, it's what I was thinking of as well. Not every plugin/mod follows the version scheme of spigot/fabric, especially with beta/alpha releases.
The solution you mention seems good to me (of course it needs to be checked for the MC version, but I bet that's already happening).

**Comment by DeathsGun** [comment]
Yeah it filters automatically for the fabric loader and the correct mc version

**Comment by DeathsGun** [comment]
Can you test the fix?

[modmanager-1.1.0+1.17-alpha.jar.zip](https://github.com/DeathsGun/ModManager/files/7239334/modmanager-1.1.0%2B1.17-alpha.jar.zip)

**Comment by FPSUsername** [comment]
Tried it, but unfortunately, mousewheelie isn't showing up anymore as outdated.
However, I found new issues:
Current latest release of lithium on [modrinth](https://modrinth.com/mod/lithium/versions) is 0.7.4, which I have installed.
![image](https://user-images.githubusercontent.com/10143926/135089549-cff766fc-aca5-421f-a87e-7db919d4e996.png)

Headsdown display on [modrinth](https://modrinth.com/mod/heads-down-display/versions) is version 0.1.1, which I also have installed, yet the mod manager thinks it's version 0.0.0.
![image](https://user-images.githubusercontent.com/10143926/135090011-743a354e-053e-4440-bbea-3aa7116ce3cb.png)

**Comment by RDKRACZ** [comment]
>Heads down display is version 0.1.1, which I also have installed, yet the mod manager thinks it's version 0.0.0.

This issue is caused by the Heads down display itself - https://github.com/auoeke/heads-down-display/blob/1.17/src/main/resources/fabric.mod.json

**Comment by DeathsGun** [comment]
I would suggest the following:
- [ ] Moving the version comparing logic in an own class so it can be used in tests
- [ ] Writing tests that will specifically target such invalid version numbers
- [ ] **Most important** Testing other SemVer libraries which maybe are more complete than fabric's implementation

**Comment by DeathsGun** [comment]
This version improves it a bit, but for mods who are declaring different version id's on modrinth and in their metadata is something I can't fix. You could only ask them nicely if they would follow the SemVer spec and only use the name field for differentiating between forge and fabric versions.

[modmanager-1.1.0+1.17-alpha.jar.zip](https://github.com/DeathsGun/ModManager/files/7254167/modmanager-1.1.0%2B1.17-alpha.jar.zip)

**Comment by DeathsGun** [comment]
If the anymore issues with versions not following SemVer then please consider asking the mod author to change their versioning
