### ISSUE TITLE
[BUG] Forge mod versions marked as updates

### ISSUE THREAD

**Issue by Felix14-v2** [DeathsGun/ModManager#56]
[[Demo]](https://youtu.be/xwaGzshsNPU)

**Technical info**
 - Windows 10
 - Minecraft version 1.17.1
 - ModManager 1.1.0+1.17-alpha

**Logs**
[latest.log](https://github.com/DeathsGun/ModManager/files/7190209/latest.log)

**Additional information**
It really loads Forge version (⓿_⓿)
![image](https://user-images.githubusercontent.com/75726196/133894790-6b08e732-ef30-4cff-820b-09dfb7ba7dd2.png)

**Comment by DeathsGun** [comment]
Looks like MemoryUsageScreen isn't following the SemVer spec but also ModManager should have catches that it contains Forge so it's a bug
