### ISSUE TITLE
[FEATURE] Ignore mods that do not use Modrinth

### ISSUE THREAD

**Issue by DeJayDev** [DeathsGun/ModManager#62]
Please ignore the modid's `essential-loader` and `essential`.

[Essential, distributed by ModCore Inc.,](https://essential.gg) uses its own updater and I believe that checking them on Modrinth is a waste of an API call.

Obviously this isn't "required" and not skipping it wouldn't hurt anyone but it could serve as the basis of a growing list of mods that cannot be updated on Modrinth.

I've provided a link to Essential, it's hyperlinked above.

**Comment by DeathsGun** [comment]
Maintaining a list of mods that shouldn't be able to be updated through ModManager is I think out of scope.
I can only provide a JSON file in which users can disable update checks for specific mods themselfs. Or an option for mods to disable it via `fabric.mod.json`
