### ISSUE TITLE
[BUG] Error on console when launching with figura mod

### ISSUE THREAD

**Issue by davidalb97** [DeathsGun/ModManager#70]
**Describe the bug**
Installing [figura](https://modrinth.com/mod/figura) mod causes an error on the log when running with mod manager:
```
[DefaultDispatcher-worker-2/INFO]: No update for modmanager found!
[DefaultDispatcher-worker-4/INFO]: No update for modmenu found!
[DefaultDispatcher-worker-4/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.fabricmc.loader.api.SemanticVersion.getVersionComponentCount()" because "o" is null
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at net.fabricmc.loader.util.version.SemanticVersionImpl.compareTo(SemanticVersionImpl.java:228)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.VersionFinder.findUpdateByVersion$modmanager(VersionFinder.kt:72)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.VersionFinder.findUpdate(VersionFinder.kt:85)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.checkForUpdatesManually(UpdateManager.kt:148)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager.access$checkForUpdatesManually(UpdateManager.kt:56)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at xyz.deathsgun.modmanager.update.UpdateManager$checkUpdates$2$1$1.invokeSuspend(UpdateManager.kt:76)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[DefaultDispatcher-worker-4/INFO]: [STDERR]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**To Reproduce**
1. Install mods from modlist bellow
2. Launch minecraft

**Expected behavior**
No error on the console.

**Please complete the following information:**
 - OS: Manjaro Li
 - Minecraft version 1.17.1
 - Version [e.g. 1.0.0-alpha]
- OS: Manjaro Linux x86_64 
- Kernel: 5.13.19-2-MANJARO 
- Uptime: 2 hours, 23 mins 
- Shell: bash 5.1.8 
- Resolution: 1050x1680, 1920x1080, 1920x1080 
- DE: Plasma 5.22.5 
- WM: KWin 
- Theme: Breath2 2021 Dark [Plasma], Matcha-dark-aliz [GTK2/3] 
- Icons: [Plasma], breath2 [GTK2/3] 
- Terminal: yakuake 
- CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
- GPU: NVIDIA GeForce GTX 750 Ti
- Memory: 7459MiB / 48104MiB

**Mod list:**
- `fabric@0.40.1+1.17`
- `figura@0.0.6`
- `modmanager@1.1.0-alpha+1.17`
- `modmenu@2.0.13`

**Logs**
Latest log: https://pastebin.com/H4WpdXa3

Crash-report (if any): none

**Comment by DeathsGun** [comment]
Does this version fix your problem?

[modmanager-1.1.0-alpha+1.17.jar.zip](https://github.com/DeathsGun/ModManager/files/7271459/modmanager-1.1.0-alpha%2B1.17.jar.zip)

**Comment by davidalb97** [comment]
Yes, the problem is fixed, however, the version 1.1.0-alpha  that I was using from modrinth (and still has the error) had a SHA1: c9a267f6be2605f097247a24e19444ab8396fcc2, while the version you just gave me from github releases has a SHA1: 927fd494cf44f53022888ab93078eb69be24fac7.

**Comment by DeathsGun** [comment]
yes i gave you a build of #71

**Comment by davidalb97** [comment]
Thanks for clearing it out, was getting a little bit confused :+1:

**Comment by DeathsGun** [comment]
No problem
