### ISSUE TITLE
[Bug] Modmanager downloads Forge artifacts

### ISSUE THREAD

**Issue by CreeperCoder63** [DeathsGun/ModManager#80]
Could you add some way to detect which mod loader the mod updates are? Because it keeps prompting me to update to the forge version of mods when I am using fabric. 

Thanks

**Comment by CreeperCoder63** [comment]
> Which ModManager version are you using?

I am currently using 1.0.2

**Comment by DeathsGun** [comment]
Update to [v1.1.1+.17](https://modrinth.com/mod/modmanager/version/JiDSrPNe)
_(Note: As of 1.1.0 ModManager uses [fabric-language-kotlin](https://modrinth.com/mod/fabric-language-kotlin/version/1qsZV7U7))_
