### ISSUE TITLE
Essential compatibility – Error checking for updates of all mods

### ISSUE THREAD

**Issue by Felix14-v2** [DeathsGun/ModManager#84]
**Description**
When Essential and ModManager are installed, Mod Manager cannot check for updates at all with this messages in logs:
«Skipping update for [ModName] because it has no jar in mods»

**To Reproduce**
1. Install ModManager
2. Install an outdated version of any example mod from Modrinth
3. Install [Essential](https://essential.gg)
4. Launch Minecraft 1.17.1
5. Open ModManager menu
6. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/75726196/137586483-82f9765f-41a2-4ce2-91c4-1a142dba35de.png)

**Technical Info:**
 - OS: Windows 10
 - Minecraft: 1.17.1
 - ModManager version: 1.1.1

**Logs**
Without Essential: [latest.log](https://github.com/DeathsGun/ModManager/files/7357483/latest.log)
With Essential: [latest.log](https://github.com/DeathsGun/ModManager/files/7357486/latest.log)

**Comment by DeathsGun** [comment]
I can't reproduce it as Essential crashes for me in the dev environment. First because I was using fabricloader 0.12 and after rolling back to 0.11 it crashed with a Linkage error. I tried it on Linux and macOS always this error.

[crash-2021-10-18_19.06.39-client.txt](https://github.com/DeathsGun/ModManager/files/7367288/crash-2021-10-18_19.06.39-client.txt)
or

**Comment by DeathsGun** [comment]
Can you recheck this with the new version, because in #94 the setup had also essentials and update checking did work

**Comment by Felix14-v2** [comment]
Unfortunately, ModManager 1.2.0 still can't check for updates with Essential.

**Comment by DeathsGun** [comment]
I could reproduce the behavior in multimc I now just need to get this working in intellij

**Comment by DeathsGun** [comment]
Found the bug Essentials didn't provide a name in the fabric.mod.json and thats why ModManager couldn't parse it and handled the error incorrectly.
