### ISSUE TITLE
[BUG] Old version of mods still not being removed after updated

### ISSUE THREAD

**Issue by NaiNonTH** [DeathsGun/ModManager#91]
**Describe the bug**
So I updated Ears mod then I restarted the game. But fabric just showed me this.
`
Duplicate versions for mod ID 'ears': [1.4.0 at /C:/Users/NoncanbeZaza/AppData/Roaming/.minecraft/mods/ears-fabric-1.17-1.4.0.jar], [1.3.0 at /C:/Users/NoncanbeZaza/AppData/Roaming/.minecraft/mods/ears-fabric-1.17-1.3.0.jar]
`
This means that the old version of the mod was still not being removed. I know this one is another one of #51, But this is still not being removed completely.

**To Reproduce**
1. Install the old version of any mods (in modrinth)
1. Launch the game and update the mods by going to 'Mods'
2. Click on the 'Download Logo Button'
3. Double Click the mod that you've just installed
4. Click 'Update'
5. After it's finished, Go back and restart the game.
6. Launch the game again. You'll see that the fabric error will appear.

**Expected behavior**
The game launched normally with the new version of mods without showing the duplicated mod error.

**Please complete the following information:**
 - OS: Windows 10 Pro 64-bit
 - Minecraft version: 1.17.1
 - Version 1.1.1-alpha

**Comment by DeathsGun** [comment]
I cloud replicate it using the 1.1.1 version and the Minecraft launcher but not using the IDE. I need some further testing.

**Comment by DeathsGun** [comment]
The PR didn't remove the problem completely

**Comment by DeathsGun** [comment]
When removing mods you may need to restart twice to get the mod to be not loaded again.
This will be needed to be fixed in the future
