### ISSUE TITLE
[BUG] Updates alert shown, no way of accessing mod updates

### ISSUE THREAD

**Issue by keatit71** [DeathsGun/ModManager#94]
**Describe the bug**
When i load into minecraft i get a alert that there is mod updates but click on the mod manager button just lets me install mods not letting me see the updates or be able to blacklist them.

**To Reproduce**
1. Open Minecraft
2. Click on Mods
3. Click on mod manager button

**Expected behavior**
Should show mod updates

**Please complete the following information:**
 - Windows 10
 - 1.17.1
 - modmanager-1.2.0-alpha+1.17

**Logs**
Latest log:

[latest.log](https://github.com/DeathsGun/ModManager/files/7491987/latest.log)

**Comment by DeathsGun** [comment]
Blacklisting is done trough the ModMenu UI you should see a button with an eye there to hide updates.

Also you should use fabricloader 0.12 and not 0.11

**Comment by keatit71** [comment]
I cant see any eye button since updates dont show and im on newest fabric loader

**Comment by DeathsGun** [comment]
Latest Fabric-Loader is 0.12.5 you need to scroll up in the selector:
![image](https://user-images.githubusercontent.com/13536793/140639341-0a2306d4-88cc-4b6c-aadf-40aae097bd65.png)

And the hiding part is done in ModMenu not ModManager via the little crossed eye button:
![image](https://user-images.githubusercontent.com/13536793/140639391-23d590ed-edc5-4d9d-bb21-6596fc1400f9.png)

**Comment by keatit71** [comment]
Ive installed the latest fabric loader through multimc which is 0.12.5 which I meant and blacklisting works just cant see the updates then

**Comment by DeathsGun** [comment]
So your problem is that the mod you blacklisted isn't showing up in the updatable mods section?

**Comment by keatit71** [comment]
No I cant see the updater section

**Comment by DeathsGun** [comment]
When mods are blacklisted they are excluded from showing up in the notification and updatable mods section. So when you blacklist a mod which has an update and no other mods has updates you need to search for the mod explicitly to update it.

**Comment by keatit71** [comment]
Im not talking about the blacklist anymore I havent blacklisted anything I cant access the updates screen

**Comment by DeathsGun** [comment]
Okay i try to recreate your setup because i can't find anything relevant in the logs

**Comment by DeathsGun** [comment]
Looks ModManager something like this for you?
![image](https://user-images.githubusercontent.com/13536793/140653260-63b3abd4-7eef-4c89-b3ff-709af0e35bed.png)

**Comment by keatit71** [comment]
Yeah, if it helps I can just send you mods and configd

**Comment by DeathsGun** [comment]
Yeah that would be nice

**Comment by keatit71** [comment]
hers the mods when you load the game it should give you a notification that mod updates are available

https://www.mediafire.com/file/eftslad5r8c6cwz/.minecraft.zip/file

**Comment by DeathsGun** [comment]
Yeah the list with the buttons is there but there are not being rendered because bedrockify changes the background and breaks the lists.
![image](https://user-images.githubusercontent.com/13536793/140654206-314c974b-fe59-4afa-aee6-6e72b4eeed1f.png)

I will open an issue there until then you will need to disable panoramaBackgrounds in the bedrockify settings

**Comment by DeathsGun** [comment]
juancarloscp52/BedrockIfy#115
