### ISSUE TITLE
Enviroments Filters

### ISSUE THREAD

**Issue by Unconventional10** [DeathsGun/ModManager#98]
**Is your feature request related to a problem? Please describe.**
I want to be able to filter by Client or Server-side

**Describe the solution you'd like**
Add Client and Server filters to the sidebar

**Additional context**
Example
![Example](https://user-images.githubusercontent.com/61166139/141173924-fd984125-90c9-4268-9a2a-d4e01a066368.png)

**Comment by DeathsGun** [comment]
Hi thank you for opening a feature request. ModManager does already filter for client side mods by default:
![Screen Shot 2021-11-10 at 19 56 49](https://user-images.githubusercontent.com/13536793/141175916-56b29bdf-d759-49d9-af73-6da05b7f7461.png)
