### ISSUE TITLE
Login to Modrinth

### ISSUE THREAD

**Issue by Aras14HD** [DeathsGun/ModManager#99]
Log into Modrinth with Github to access followed mods.

**Comment by DeathsGun** [comment]
I'm not that keen on saving credentials for github in a mod because other mods will have access too

**Comment by Aras14HD** [comment]
I was more thinking OAuth (login with GitHub) via opening the browser.
But as you said, it might not be a good idea, because all mods would theoretically have access to your Modrinth account. (but not your GitHub)
